from app.core.config import get_settings
from app.services.analytics_service import AnalyticsService
from app.services.gemini_service import GeminiNotConfiguredError, GeminiService


class AIService:
    def __init__(self, analytics: AnalyticsService):
        self.analytics = analytics

    def answer(self, question: str) -> dict:
        context = self.analytics.dataset_context(question)
        settings = get_settings()
        gemini = GeminiService(
            api_key=settings.gemini_api_key,
            model=settings.gemini_model,
        )

        try:
            answer = gemini.generate_answer(question, context)
            if answer:
                return {
                    "answer": answer,
                    "note": f"Generated by {settings.gemini_model} using NEXUS dataset context.",
                    "data_context": context,
                }
        except GeminiNotConfiguredError:
            return {
                "answer": self._fallback_answer(context),
                "note": "Gemini is not configured. Add GEMINI_API_KEY in the backend environment to enable live AI answers.",
                "data_context": context,
            }
        except Exception as error:
            return {
                "answer": self._fallback_answer(context),
                "note": f"Gemini could not answer right now: {error}",
                "data_context": context,
            }

        return {
            "answer": self._fallback_answer(context),
            "note": "Gemini returned an empty answer, so NEXUS used the local dataset context fallback.",
            "data_context": context,
        }

    def _fallback_answer(self, context: dict) -> str:
        matched_countries = context["matched_countries"]
        matched_products = context["matched_products"]

        parts = ["NEXUS found dataset context for your question."]
        if matched_countries:
            parts.append(f"Countries: {', '.join(matched_countries)}.")
        if matched_products:
            parts.append(f"Products: {', '.join(matched_products)}.")
        if not matched_countries and not matched_products:
            parts.append("Ask about a country, product, yield trend, or comparison available in the dataset.")

        summary = context.get("summary", {})
        if summary:
            parts.append(
                "The dataset includes "
                f"{summary.get('total_records', 0)} records across "
                f"{summary.get('total_countries', 0)} countries and "
                f"{summary.get('total_products', 0)} products."
            )

        return " ".join(parts)
